[workspace]
default-members = ["shared"]
members = ["server", "shared"]

[patch.crates-io]
chrono = {git = "https://github.com/dovahcrow/chrono"}
rust_decimal = {git = "https://github.com/dovahcrow/rust-decimal"}
